"""
    Darkclaw API

    A modern, stable interface to game data sourced from Darkpaw Games Census. Darkclaw normalizes upstream paths, parameters, payloads, pagination, and errors so consumers never need to depend on Census-specific conventions.  Darkclaw is unofficial and is not affiliated with or endorsed by Darkpaw Games. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from darkclaw_census_api_client.models.generic_record_page import GenericRecordPage
from darkclaw_census_api_client.models.generic_record_response import GenericRecordResponse

from darkclaw_census_api_client.api_client import ApiClient, RequestSerialized
from darkclaw_census_api_client.api_response import ApiResponse
from darkclaw_census_api_client.rest import RESTResponseType


class RecordsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_collection_record(
        self,
        game_id: Annotated[StrictStr, Field(description="Stable Darkclaw game identifier.")],
        collection_id: Annotated[str, Field(strict=True)],
        record_id: Annotated[str, Field(min_length=1, strict=True)],
        fields: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Comma-separated response fields to include.")] = None,
        language: Annotated[Optional[StrictStr], Field(description="Preferred language for localized values.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GenericRecordResponse:
        """Get an untyped collection record


        :param game_id: Stable Darkclaw game identifier. (required)
        :type game_id: str
        :param collection_id: (required)
        :type collection_id: str
        :param record_id: (required)
        :type record_id: str
        :param fields: Comma-separated response fields to include.
        :type fields: str
        :param language: Preferred language for localized values.
        :type language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_collection_record_serialize(
            game_id=game_id,
            collection_id=collection_id,
            record_id=record_id,
            fields=fields,
            language=language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GenericRecordResponse",
            '404': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_collection_record_with_http_info(
        self,
        game_id: Annotated[StrictStr, Field(description="Stable Darkclaw game identifier.")],
        collection_id: Annotated[str, Field(strict=True)],
        record_id: Annotated[str, Field(min_length=1, strict=True)],
        fields: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Comma-separated response fields to include.")] = None,
        language: Annotated[Optional[StrictStr], Field(description="Preferred language for localized values.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GenericRecordResponse]:
        """Get an untyped collection record


        :param game_id: Stable Darkclaw game identifier. (required)
        :type game_id: str
        :param collection_id: (required)
        :type collection_id: str
        :param record_id: (required)
        :type record_id: str
        :param fields: Comma-separated response fields to include.
        :type fields: str
        :param language: Preferred language for localized values.
        :type language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_collection_record_serialize(
            game_id=game_id,
            collection_id=collection_id,
            record_id=record_id,
            fields=fields,
            language=language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GenericRecordResponse",
            '404': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_collection_record_without_preload_content(
        self,
        game_id: Annotated[StrictStr, Field(description="Stable Darkclaw game identifier.")],
        collection_id: Annotated[str, Field(strict=True)],
        record_id: Annotated[str, Field(min_length=1, strict=True)],
        fields: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Comma-separated response fields to include.")] = None,
        language: Annotated[Optional[StrictStr], Field(description="Preferred language for localized values.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get an untyped collection record


        :param game_id: Stable Darkclaw game identifier. (required)
        :type game_id: str
        :param collection_id: (required)
        :type collection_id: str
        :param record_id: (required)
        :type record_id: str
        :param fields: Comma-separated response fields to include.
        :type fields: str
        :param language: Preferred language for localized values.
        :type language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_collection_record_serialize(
            game_id=game_id,
            collection_id=collection_id,
            record_id=record_id,
            fields=fields,
            language=language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GenericRecordResponse",
            '404': "Problem",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_collection_record_serialize(
        self,
        game_id,
        collection_id,
        record_id,
        fields,
        language,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if game_id is not None:
            _path_params['gameId'] = game_id
        if collection_id is not None:
            _path_params['collectionId'] = collection_id
        if record_id is not None:
            _path_params['recordId'] = record_id
        # process the query parameters
        if fields is not None:
            
            _query_params.append(('fields', fields))
            
        if language is not None:
            
            _query_params.append(('language', language))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/problem+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/games/{gameId}/collections/{collectionId}/records/{recordId}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_collection_records(
        self,
        game_id: Annotated[StrictStr, Field(description="Stable Darkclaw game identifier.")],
        collection_id: Annotated[str, Field(strict=True)],
        page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Maximum records returned in this page.")] = None,
        cursor: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Opaque cursor returned by the previous page.")] = None,
        fields: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Comma-separated response fields to include.")] = None,
        sort: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Comma-separated fields, prefixed with `-` for descending order.")] = None,
        language: Annotated[Optional[StrictStr], Field(description="Preferred language for localized values.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GenericRecordPage:
        """List records from an untyped collection

        Advanced escape hatch for collections that do not yet have a typed Darkclaw resource. Prefer a typed endpoint when one exists. 

        :param game_id: Stable Darkclaw game identifier. (required)
        :type game_id: str
        :param collection_id: (required)
        :type collection_id: str
        :param page_size: Maximum records returned in this page.
        :type page_size: int
        :param cursor: Opaque cursor returned by the previous page.
        :type cursor: str
        :param fields: Comma-separated response fields to include.
        :type fields: str
        :param sort: Comma-separated fields, prefixed with `-` for descending order.
        :type sort: str
        :param language: Preferred language for localized values.
        :type language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_collection_records_serialize(
            game_id=game_id,
            collection_id=collection_id,
            page_size=page_size,
            cursor=cursor,
            fields=fields,
            sort=sort,
            language=language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GenericRecordPage",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_collection_records_with_http_info(
        self,
        game_id: Annotated[StrictStr, Field(description="Stable Darkclaw game identifier.")],
        collection_id: Annotated[str, Field(strict=True)],
        page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Maximum records returned in this page.")] = None,
        cursor: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Opaque cursor returned by the previous page.")] = None,
        fields: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Comma-separated response fields to include.")] = None,
        sort: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Comma-separated fields, prefixed with `-` for descending order.")] = None,
        language: Annotated[Optional[StrictStr], Field(description="Preferred language for localized values.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GenericRecordPage]:
        """List records from an untyped collection

        Advanced escape hatch for collections that do not yet have a typed Darkclaw resource. Prefer a typed endpoint when one exists. 

        :param game_id: Stable Darkclaw game identifier. (required)
        :type game_id: str
        :param collection_id: (required)
        :type collection_id: str
        :param page_size: Maximum records returned in this page.
        :type page_size: int
        :param cursor: Opaque cursor returned by the previous page.
        :type cursor: str
        :param fields: Comma-separated response fields to include.
        :type fields: str
        :param sort: Comma-separated fields, prefixed with `-` for descending order.
        :type sort: str
        :param language: Preferred language for localized values.
        :type language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_collection_records_serialize(
            game_id=game_id,
            collection_id=collection_id,
            page_size=page_size,
            cursor=cursor,
            fields=fields,
            sort=sort,
            language=language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GenericRecordPage",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_collection_records_without_preload_content(
        self,
        game_id: Annotated[StrictStr, Field(description="Stable Darkclaw game identifier.")],
        collection_id: Annotated[str, Field(strict=True)],
        page_size: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="Maximum records returned in this page.")] = None,
        cursor: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Opaque cursor returned by the previous page.")] = None,
        fields: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Comma-separated response fields to include.")] = None,
        sort: Annotated[Optional[Annotated[str, Field(min_length=1, strict=True)]], Field(description="Comma-separated fields, prefixed with `-` for descending order.")] = None,
        language: Annotated[Optional[StrictStr], Field(description="Preferred language for localized values.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List records from an untyped collection

        Advanced escape hatch for collections that do not yet have a typed Darkclaw resource. Prefer a typed endpoint when one exists. 

        :param game_id: Stable Darkclaw game identifier. (required)
        :type game_id: str
        :param collection_id: (required)
        :type collection_id: str
        :param page_size: Maximum records returned in this page.
        :type page_size: int
        :param cursor: Opaque cursor returned by the previous page.
        :type cursor: str
        :param fields: Comma-separated response fields to include.
        :type fields: str
        :param sort: Comma-separated fields, prefixed with `-` for descending order.
        :type sort: str
        :param language: Preferred language for localized values.
        :type language: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_collection_records_serialize(
            game_id=game_id,
            collection_id=collection_id,
            page_size=page_size,
            cursor=cursor,
            fields=fields,
            sort=sort,
            language=language,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GenericRecordPage",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_collection_records_serialize(
        self,
        game_id,
        collection_id,
        page_size,
        cursor,
        fields,
        sort,
        language,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if game_id is not None:
            _path_params['gameId'] = game_id
        if collection_id is not None:
            _path_params['collectionId'] = collection_id
        # process the query parameters
        if page_size is not None:
            
            _query_params.append(('pageSize', page_size))
            
        if cursor is not None:
            
            _query_params.append(('cursor', cursor))
            
        if fields is not None:
            
            _query_params.append(('fields', fields))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if language is not None:
            
            _query_params.append(('language', language))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/problem+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/games/{gameId}/collections/{collectionId}/records',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


