# coding: utf-8

# flake8: noqa

"""
    Darkclaw API

    A modern, stable interface to game data sourced from Darkpaw Games Census. Darkclaw normalizes upstream paths, parameters, payloads, pagination, and errors so consumers never need to depend on Census-specific conventions.  Darkclaw is unofficial and is not affiliated with or endorsed by Darkpaw Games. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.2.0"

# Define package exports
__all__ = [
    "DiscoveryApi",
    "EverQuestIICharactersApi",
    "RecordsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Character",
    "CharacterLocation",
    "CharacterName",
    "CharacterPage",
    "CharacterProfile",
    "CharacterResponse",
    "Collection",
    "CollectionListResponse",
    "GenericRecordPage",
    "GenericRecordResponse",
    "PageMetadata",
    "Problem",
]

# import apis into sdk package
from darkclaw_census_api_client.api.discovery_api import DiscoveryApi as DiscoveryApi
from darkclaw_census_api_client.api.ever_quest_ii_characters_api import EverQuestIICharactersApi as EverQuestIICharactersApi
from darkclaw_census_api_client.api.records_api import RecordsApi as RecordsApi

# import ApiClient
from darkclaw_census_api_client.api_response import ApiResponse as ApiResponse
from darkclaw_census_api_client.api_client import ApiClient as ApiClient
from darkclaw_census_api_client.configuration import Configuration as Configuration
from darkclaw_census_api_client.exceptions import OpenApiException as OpenApiException
from darkclaw_census_api_client.exceptions import ApiTypeError as ApiTypeError
from darkclaw_census_api_client.exceptions import ApiValueError as ApiValueError
from darkclaw_census_api_client.exceptions import ApiKeyError as ApiKeyError
from darkclaw_census_api_client.exceptions import ApiAttributeError as ApiAttributeError
from darkclaw_census_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from darkclaw_census_api_client.models.character import Character as Character
from darkclaw_census_api_client.models.character_location import CharacterLocation as CharacterLocation
from darkclaw_census_api_client.models.character_name import CharacterName as CharacterName
from darkclaw_census_api_client.models.character_page import CharacterPage as CharacterPage
from darkclaw_census_api_client.models.character_profile import CharacterProfile as CharacterProfile
from darkclaw_census_api_client.models.character_response import CharacterResponse as CharacterResponse
from darkclaw_census_api_client.models.collection import Collection as Collection
from darkclaw_census_api_client.models.collection_list_response import CollectionListResponse as CollectionListResponse
from darkclaw_census_api_client.models.generic_record_page import GenericRecordPage as GenericRecordPage
from darkclaw_census_api_client.models.generic_record_response import GenericRecordResponse as GenericRecordResponse
from darkclaw_census_api_client.models.page_metadata import PageMetadata as PageMetadata
from darkclaw_census_api_client.models.problem import Problem as Problem

