# coding: utf-8

"""
    Darkclaw API

    A modern, stable interface to game data sourced from Darkpaw Games Census. Darkclaw normalizes upstream paths, parameters, payloads, pagination, and errors so consumers never need to depend on Census-specific conventions.  Darkclaw is unofficial and is not affiliated with or endorsed by Darkpaw Games. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CharacterLocation(BaseModel):
    """
    CharacterLocation
    """ # noqa: E501
    server_id: Optional[StrictInt] = Field(default=None, alias="serverId")
    server_name: Optional[StrictStr] = Field(default=None, alias="serverName")
    zone_name: Optional[StrictStr] = Field(default=None, alias="zoneName")
    coordinates: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["serverId", "serverName", "zoneName", "coordinates"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CharacterLocation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if server_id (nullable) is None
        # and model_fields_set contains the field
        if self.server_id is None and "server_id" in self.model_fields_set:
            _dict['serverId'] = None

        # set to None if server_name (nullable) is None
        # and model_fields_set contains the field
        if self.server_name is None and "server_name" in self.model_fields_set:
            _dict['serverName'] = None

        # set to None if zone_name (nullable) is None
        # and model_fields_set contains the field
        if self.zone_name is None and "zone_name" in self.model_fields_set:
            _dict['zoneName'] = None

        # set to None if coordinates (nullable) is None
        # and model_fields_set contains the field
        if self.coordinates is None and "coordinates" in self.model_fields_set:
            _dict['coordinates'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CharacterLocation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "serverId": obj.get("serverId"),
            "serverName": obj.get("serverName"),
            "zoneName": obj.get("zoneName"),
            "coordinates": obj.get("coordinates")
        })
        return _obj


