# coding: utf-8

"""
    Darkclaw API

    A modern, stable interface to game data sourced from Darkpaw Games Census. Darkclaw normalizes upstream paths, parameters, payloads, pagination, and errors so consumers never need to depend on Census-specific conventions.  Darkclaw is unofficial and is not affiliated with or endorsed by Darkpaw Games. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CharacterProfile(BaseModel):
    """
    CharacterProfile
    """ # noqa: E501
    class_id: Optional[StrictInt] = Field(default=None, alias="classId")
    class_name: Optional[StrictStr] = Field(default=None, alias="className")
    race_id: Optional[StrictInt] = Field(default=None, alias="raceId")
    race_name: Optional[StrictStr] = Field(default=None, alias="raceName")
    level: Optional[Annotated[int, Field(strict=True, ge=1)]] = None
    gender: Optional[StrictStr] = None
    deity: Optional[StrictStr] = None
    alignment: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["classId", "className", "raceId", "raceName", "level", "gender", "deity", "alignment"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CharacterProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if class_id (nullable) is None
        # and model_fields_set contains the field
        if self.class_id is None and "class_id" in self.model_fields_set:
            _dict['classId'] = None

        # set to None if class_name (nullable) is None
        # and model_fields_set contains the field
        if self.class_name is None and "class_name" in self.model_fields_set:
            _dict['className'] = None

        # set to None if race_id (nullable) is None
        # and model_fields_set contains the field
        if self.race_id is None and "race_id" in self.model_fields_set:
            _dict['raceId'] = None

        # set to None if race_name (nullable) is None
        # and model_fields_set contains the field
        if self.race_name is None and "race_name" in self.model_fields_set:
            _dict['raceName'] = None

        # set to None if level (nullable) is None
        # and model_fields_set contains the field
        if self.level is None and "level" in self.model_fields_set:
            _dict['level'] = None

        # set to None if gender (nullable) is None
        # and model_fields_set contains the field
        if self.gender is None and "gender" in self.model_fields_set:
            _dict['gender'] = None

        # set to None if deity (nullable) is None
        # and model_fields_set contains the field
        if self.deity is None and "deity" in self.model_fields_set:
            _dict['deity'] = None

        # set to None if alignment (nullable) is None
        # and model_fields_set contains the field
        if self.alignment is None and "alignment" in self.model_fields_set:
            _dict['alignment'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CharacterProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "classId": obj.get("classId"),
            "className": obj.get("className"),
            "raceId": obj.get("raceId"),
            "raceName": obj.get("raceName"),
            "level": obj.get("level"),
            "gender": obj.get("gender"),
            "deity": obj.get("deity"),
            "alignment": obj.get("alignment")
        })
        return _obj


