/* tslint:disable */
/* eslint-disable */
/**
 * Monorepo API
 * The public contract shared by the Laravel API, Flutter application, and React website. Change this document before changing public API behavior. 
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatusResponse
 */
export interface StatusResponse {
    /**
     * 
     * @type {StatusResponseStatusEnum}
     * @memberof StatusResponse
     */
    status: StatusResponseStatusEnum;
    /**
     * 
     * @type {StatusResponseServiceEnum}
     * @memberof StatusResponse
     */
    service: StatusResponseServiceEnum;
    /**
     * 
     * @type {Date}
     * @memberof StatusResponse
     */
    timestamp: Date;
}


/**
 * @export
 */
export const StatusResponseStatusEnum = {
    Ok: 'ok'
} as const;
export type StatusResponseStatusEnum = typeof StatusResponseStatusEnum[keyof typeof StatusResponseStatusEnum];

/**
 * @export
 */
export const StatusResponseServiceEnum = {
    MonorepoApi: 'monorepo-api'
} as const;
export type StatusResponseServiceEnum = typeof StatusResponseServiceEnum[keyof typeof StatusResponseServiceEnum];


/**
 * Check if a given object implements the StatusResponse interface.
 */
export function instanceOfStatusResponse(value: object): value is StatusResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function StatusResponseFromJSON(json: any): StatusResponse {
    return StatusResponseFromJSONTyped(json, false);
}

export function StatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'service': json['service'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function StatusResponseToJSON(json: any): StatusResponse {
    return StatusResponseToJSONTyped(json, false);
}

export function StatusResponseToJSONTyped(value?: StatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'service': value['service'],
        'timestamp': value['timestamp'].toISOString(),
    };
}

