/* tslint:disable */
/* eslint-disable */
/**
 * Darkclaw API
 * A modern, stable interface to game data sourced from Darkpaw Games Census. Darkclaw normalizes upstream paths, parameters, payloads, pagination, and errors so consumers never need to depend on Census-specific conventions.  Darkclaw is unofficial and is not affiliated with or endorsed by Darkpaw Games. 
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Character {
    'id': string;
    'name': CharacterName;
    'displayName'?: string | null;
    'profile'?: CharacterProfile;
    'location'?: CharacterLocation;
    'updatedAt'?: string | null;
}
export interface CharacterLocation {
    'serverId'?: number | null;
    'serverName'?: string | null;
    'zoneName'?: string | null;
    'coordinates'?: string | null;
}
export interface CharacterName {
    'first': string;
    'last'?: string | null;
}
export interface CharacterPage {
    'data': Array<Character>;
    'page': PageMetadata;
}
export interface CharacterProfile {
    'classId'?: number | null;
    'className'?: string | null;
    'raceId'?: number | null;
    'raceName'?: string | null;
    'level'?: number | null;
    'gender'?: string | null;
    'deity'?: string | null;
    'alignment'?: number | null;
}
export interface CharacterResponse {
    'data': Character;
}
export interface Collection {
    'id': string;
    'recordCount': number;
    'hidden': boolean;
    'indexes': Array<Array<string>>;
    'resolvers': Array<string>;
}
export interface CollectionListResponse {
    'data': Array<Collection>;
}
export interface GenericRecordPage {
    'data': Array<{ [key: string]: any | undefined; }>;
    'page': PageMetadata;
}
export interface GenericRecordResponse {
    /**
     * Untyped upstream record retained as an advanced escape hatch.
     */
    'data': { [key: string]: any | undefined; };
}
export interface PageMetadata {
    'pageSize': number;
    'returned': number;
    'nextCursor': string | null;
}
/**
 * RFC 9457 problem details.
 */
export interface Problem {
    [key: string]: any;

    'type': string;
    'title': string;
    'status': number;
    'detail'?: string;
    'instance'?: string;
}

/**
 * DiscoveryApi - axios parameter creator
 */
export const DiscoveryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Lists the upstream data collections available for a supported game.
         * @summary List available collections
         * @param {ListCollectionsGameIdEnum} gameId Stable Darkclaw game identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCollections: async (gameId: ListCollectionsGameIdEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'gameId' is not null or undefined
            assertParamExists('listCollections', 'gameId', gameId)
            const localVarPath = `/v1/games/{gameId}/collections`
                .replace('{gameId}', encodeURIComponent(String(gameId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DiscoveryApi - functional programming interface
 */
export const DiscoveryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DiscoveryApiAxiosParamCreator(configuration)
    return {
        /**
         * Lists the upstream data collections available for a supported game.
         * @summary List available collections
         * @param {ListCollectionsGameIdEnum} gameId Stable Darkclaw game identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCollections(gameId: ListCollectionsGameIdEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CollectionListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCollections(gameId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DiscoveryApi.listCollections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DiscoveryApi - factory interface
 */
export const DiscoveryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DiscoveryApiFp(configuration)
    return {
        /**
         * Lists the upstream data collections available for a supported game.
         * @summary List available collections
         * @param {DiscoveryApiListCollectionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCollections(requestParameters: DiscoveryApiListCollectionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<CollectionListResponse> {
            return localVarFp.listCollections(requestParameters.gameId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DiscoveryApi - interface
 */
export interface DiscoveryApiInterface {
    /**
     * Lists the upstream data collections available for a supported game.
     * @summary List available collections
     * @param {DiscoveryApiListCollectionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCollections(requestParameters: DiscoveryApiListCollectionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<CollectionListResponse>;

}

/**
 * Request parameters for listCollections operation in DiscoveryApi.
 */
export interface DiscoveryApiListCollectionsRequest {
    /**
     * Stable Darkclaw game identifier.
     */
    readonly gameId: ListCollectionsGameIdEnum
}

/**
 * DiscoveryApi - object-oriented interface
 */
export class DiscoveryApi extends BaseAPI implements DiscoveryApiInterface {
    /**
     * Lists the upstream data collections available for a supported game.
     * @summary List available collections
     * @param {DiscoveryApiListCollectionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listCollections(requestParameters: DiscoveryApiListCollectionsRequest, options?: RawAxiosRequestConfig) {
        return DiscoveryApiFp(this.configuration).listCollections(requestParameters.gameId, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ListCollectionsGameIdEnum = {
    Eq: 'eq',
    Eq2: 'eq2',
    Mtg: 'mtg',
    Dcu: 'dcu',
    Ps: 'ps',
    Ps2: 'ps2',
    Ps2ps4us: 'ps2ps4us',
    Ps2ps4eu: 'ps2ps4eu',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type ListCollectionsGameIdEnum = typeof ListCollectionsGameIdEnum[keyof typeof ListCollectionsGameIdEnum];


/**
 * EverQuestIICharactersApi - axios parameter creator
 */
export const EverQuestIICharactersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get an EverQuest II character
         * @param {string} characterId 
         * @param {string} [fields] Comma-separated response fields to include.
         * @param {GetCharacterLanguageEnum} [language] Preferred language for localized values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCharacter: async (characterId: string, fields?: string, language?: GetCharacterLanguageEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'characterId' is not null or undefined
            assertParamExists('getCharacter', 'characterId', characterId)
            const localVarPath = `/v1/games/eq2/characters/{characterId}`
                .replace('{characterId}', encodeURIComponent(String(characterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search EverQuest II characters
         * @param {number} [pageSize] Maximum records returned in this page.
         * @param {string} [cursor] Opaque cursor returned by the previous page.
         * @param {string} [fields] Comma-separated response fields to include.
         * @param {string} [name] Exact character first name.
         * @param {string} [server] Exact server name.
         * @param {string} [className] Exact adventure class name.
         * @param {number} [minimumLevel] 
         * @param {number} [maximumLevel] 
         * @param {ListCharactersSortEnum} [sort] Character field, prefixed with &#x60;-&#x60; for descending order.
         * @param {ListCharactersLanguageEnum} [language] Preferred language for localized values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCharacters: async (pageSize?: number, cursor?: string, fields?: string, name?: string, server?: string, className?: string, minimumLevel?: number, maximumLevel?: number, sort?: ListCharactersSortEnum, language?: ListCharactersLanguageEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/games/eq2/characters`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (server !== undefined) {
                localVarQueryParameter['server'] = server;
            }

            if (className !== undefined) {
                localVarQueryParameter['className'] = className;
            }

            if (minimumLevel !== undefined) {
                localVarQueryParameter['minimumLevel'] = minimumLevel;
            }

            if (maximumLevel !== undefined) {
                localVarQueryParameter['maximumLevel'] = maximumLevel;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EverQuestIICharactersApi - functional programming interface
 */
export const EverQuestIICharactersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EverQuestIICharactersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get an EverQuest II character
         * @param {string} characterId 
         * @param {string} [fields] Comma-separated response fields to include.
         * @param {GetCharacterLanguageEnum} [language] Preferred language for localized values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCharacter(characterId: string, fields?: string, language?: GetCharacterLanguageEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CharacterResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCharacter(characterId, fields, language, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EverQuestIICharactersApi.getCharacter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search EverQuest II characters
         * @param {number} [pageSize] Maximum records returned in this page.
         * @param {string} [cursor] Opaque cursor returned by the previous page.
         * @param {string} [fields] Comma-separated response fields to include.
         * @param {string} [name] Exact character first name.
         * @param {string} [server] Exact server name.
         * @param {string} [className] Exact adventure class name.
         * @param {number} [minimumLevel] 
         * @param {number} [maximumLevel] 
         * @param {ListCharactersSortEnum} [sort] Character field, prefixed with &#x60;-&#x60; for descending order.
         * @param {ListCharactersLanguageEnum} [language] Preferred language for localized values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCharacters(pageSize?: number, cursor?: string, fields?: string, name?: string, server?: string, className?: string, minimumLevel?: number, maximumLevel?: number, sort?: ListCharactersSortEnum, language?: ListCharactersLanguageEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CharacterPage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCharacters(pageSize, cursor, fields, name, server, className, minimumLevel, maximumLevel, sort, language, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EverQuestIICharactersApi.listCharacters']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EverQuestIICharactersApi - factory interface
 */
export const EverQuestIICharactersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EverQuestIICharactersApiFp(configuration)
    return {
        /**
         * 
         * @summary Get an EverQuest II character
         * @param {EverQuestIICharactersApiGetCharacterRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCharacter(requestParameters: EverQuestIICharactersApiGetCharacterRequest, options?: RawAxiosRequestConfig): AxiosPromise<CharacterResponse> {
            return localVarFp.getCharacter(requestParameters.characterId, requestParameters.fields, requestParameters.language, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search EverQuest II characters
         * @param {EverQuestIICharactersApiListCharactersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCharacters(requestParameters: EverQuestIICharactersApiListCharactersRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CharacterPage> {
            return localVarFp.listCharacters(requestParameters.pageSize, requestParameters.cursor, requestParameters.fields, requestParameters.name, requestParameters.server, requestParameters.className, requestParameters.minimumLevel, requestParameters.maximumLevel, requestParameters.sort, requestParameters.language, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EverQuestIICharactersApi - interface
 */
export interface EverQuestIICharactersApiInterface {
    /**
     * 
     * @summary Get an EverQuest II character
     * @param {EverQuestIICharactersApiGetCharacterRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCharacter(requestParameters: EverQuestIICharactersApiGetCharacterRequest, options?: RawAxiosRequestConfig): AxiosPromise<CharacterResponse>;

    /**
     * 
     * @summary Search EverQuest II characters
     * @param {EverQuestIICharactersApiListCharactersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCharacters(requestParameters?: EverQuestIICharactersApiListCharactersRequest, options?: RawAxiosRequestConfig): AxiosPromise<CharacterPage>;

}

/**
 * Request parameters for getCharacter operation in EverQuestIICharactersApi.
 */
export interface EverQuestIICharactersApiGetCharacterRequest {
    readonly characterId: string

    /**
     * Comma-separated response fields to include.
     */
    readonly fields?: string

    /**
     * Preferred language for localized values.
     */
    readonly language?: GetCharacterLanguageEnum
}

/**
 * Request parameters for listCharacters operation in EverQuestIICharactersApi.
 */
export interface EverQuestIICharactersApiListCharactersRequest {
    /**
     * Maximum records returned in this page.
     */
    readonly pageSize?: number

    /**
     * Opaque cursor returned by the previous page.
     */
    readonly cursor?: string

    /**
     * Comma-separated response fields to include.
     */
    readonly fields?: string

    /**
     * Exact character first name.
     */
    readonly name?: string

    /**
     * Exact server name.
     */
    readonly server?: string

    /**
     * Exact adventure class name.
     */
    readonly className?: string

    readonly minimumLevel?: number

    readonly maximumLevel?: number

    /**
     * Character field, prefixed with &#x60;-&#x60; for descending order.
     */
    readonly sort?: ListCharactersSortEnum

    /**
     * Preferred language for localized values.
     */
    readonly language?: ListCharactersLanguageEnum
}

/**
 * EverQuestIICharactersApi - object-oriented interface
 */
export class EverQuestIICharactersApi extends BaseAPI implements EverQuestIICharactersApiInterface {
    /**
     * 
     * @summary Get an EverQuest II character
     * @param {EverQuestIICharactersApiGetCharacterRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCharacter(requestParameters: EverQuestIICharactersApiGetCharacterRequest, options?: RawAxiosRequestConfig) {
        return EverQuestIICharactersApiFp(this.configuration).getCharacter(requestParameters.characterId, requestParameters.fields, requestParameters.language, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search EverQuest II characters
     * @param {EverQuestIICharactersApiListCharactersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listCharacters(requestParameters: EverQuestIICharactersApiListCharactersRequest = {}, options?: RawAxiosRequestConfig) {
        return EverQuestIICharactersApiFp(this.configuration).listCharacters(requestParameters.pageSize, requestParameters.cursor, requestParameters.fields, requestParameters.name, requestParameters.server, requestParameters.className, requestParameters.minimumLevel, requestParameters.maximumLevel, requestParameters.sort, requestParameters.language, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetCharacterLanguageEnum = {
    En: 'en',
    De: 'de',
    Es: 'es',
    Fr: 'fr',
    It: 'it',
    Ja: 'ja',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type GetCharacterLanguageEnum = typeof GetCharacterLanguageEnum[keyof typeof GetCharacterLanguageEnum];
export const ListCharactersSortEnum = {
    Name: 'name',
    Name2: '-name',
    Level: 'level',
    Level2: '-level',
    UpdatedAt: 'updatedAt',
    UpdatedAt2: '-updatedAt',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type ListCharactersSortEnum = typeof ListCharactersSortEnum[keyof typeof ListCharactersSortEnum];
export const ListCharactersLanguageEnum = {
    En: 'en',
    De: 'de',
    Es: 'es',
    Fr: 'fr',
    It: 'it',
    Ja: 'ja',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type ListCharactersLanguageEnum = typeof ListCharactersLanguageEnum[keyof typeof ListCharactersLanguageEnum];


/**
 * RecordsApi - axios parameter creator
 */
export const RecordsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get an untyped collection record
         * @param {GetCollectionRecordGameIdEnum} gameId Stable Darkclaw game identifier.
         * @param {string} collectionId 
         * @param {string} recordId 
         * @param {string} [fields] Comma-separated response fields to include.
         * @param {GetCollectionRecordLanguageEnum} [language] Preferred language for localized values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCollectionRecord: async (gameId: GetCollectionRecordGameIdEnum, collectionId: string, recordId: string, fields?: string, language?: GetCollectionRecordLanguageEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'gameId' is not null or undefined
            assertParamExists('getCollectionRecord', 'gameId', gameId)
            // verify required parameter 'collectionId' is not null or undefined
            assertParamExists('getCollectionRecord', 'collectionId', collectionId)
            // verify required parameter 'recordId' is not null or undefined
            assertParamExists('getCollectionRecord', 'recordId', recordId)
            const localVarPath = `/v1/games/{gameId}/collections/{collectionId}/records/{recordId}`
                .replace('{gameId}', encodeURIComponent(String(gameId)))
                .replace('{collectionId}', encodeURIComponent(String(collectionId)))
                .replace('{recordId}', encodeURIComponent(String(recordId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Advanced escape hatch for collections that do not yet have a typed Darkclaw resource. Prefer a typed endpoint when one exists. 
         * @summary List records from an untyped collection
         * @param {ListCollectionRecordsGameIdEnum} gameId Stable Darkclaw game identifier.
         * @param {string} collectionId 
         * @param {number} [pageSize] Maximum records returned in this page.
         * @param {string} [cursor] Opaque cursor returned by the previous page.
         * @param {string} [fields] Comma-separated response fields to include.
         * @param {string} [sort] Comma-separated fields, prefixed with &#x60;-&#x60; for descending order.
         * @param {ListCollectionRecordsLanguageEnum} [language] Preferred language for localized values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCollectionRecords: async (gameId: ListCollectionRecordsGameIdEnum, collectionId: string, pageSize?: number, cursor?: string, fields?: string, sort?: string, language?: ListCollectionRecordsLanguageEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'gameId' is not null or undefined
            assertParamExists('listCollectionRecords', 'gameId', gameId)
            // verify required parameter 'collectionId' is not null or undefined
            assertParamExists('listCollectionRecords', 'collectionId', collectionId)
            const localVarPath = `/v1/games/{gameId}/collections/{collectionId}/records`
                .replace('{gameId}', encodeURIComponent(String(gameId)))
                .replace('{collectionId}', encodeURIComponent(String(collectionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecordsApi - functional programming interface
 */
export const RecordsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecordsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get an untyped collection record
         * @param {GetCollectionRecordGameIdEnum} gameId Stable Darkclaw game identifier.
         * @param {string} collectionId 
         * @param {string} recordId 
         * @param {string} [fields] Comma-separated response fields to include.
         * @param {GetCollectionRecordLanguageEnum} [language] Preferred language for localized values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCollectionRecord(gameId: GetCollectionRecordGameIdEnum, collectionId: string, recordId: string, fields?: string, language?: GetCollectionRecordLanguageEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericRecordResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCollectionRecord(gameId, collectionId, recordId, fields, language, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecordsApi.getCollectionRecord']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Advanced escape hatch for collections that do not yet have a typed Darkclaw resource. Prefer a typed endpoint when one exists. 
         * @summary List records from an untyped collection
         * @param {ListCollectionRecordsGameIdEnum} gameId Stable Darkclaw game identifier.
         * @param {string} collectionId 
         * @param {number} [pageSize] Maximum records returned in this page.
         * @param {string} [cursor] Opaque cursor returned by the previous page.
         * @param {string} [fields] Comma-separated response fields to include.
         * @param {string} [sort] Comma-separated fields, prefixed with &#x60;-&#x60; for descending order.
         * @param {ListCollectionRecordsLanguageEnum} [language] Preferred language for localized values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCollectionRecords(gameId: ListCollectionRecordsGameIdEnum, collectionId: string, pageSize?: number, cursor?: string, fields?: string, sort?: string, language?: ListCollectionRecordsLanguageEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenericRecordPage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCollectionRecords(gameId, collectionId, pageSize, cursor, fields, sort, language, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecordsApi.listCollectionRecords']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RecordsApi - factory interface
 */
export const RecordsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecordsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get an untyped collection record
         * @param {RecordsApiGetCollectionRecordRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCollectionRecord(requestParameters: RecordsApiGetCollectionRecordRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericRecordResponse> {
            return localVarFp.getCollectionRecord(requestParameters.gameId, requestParameters.collectionId, requestParameters.recordId, requestParameters.fields, requestParameters.language, options).then((request) => request(axios, basePath));
        },
        /**
         * Advanced escape hatch for collections that do not yet have a typed Darkclaw resource. Prefer a typed endpoint when one exists. 
         * @summary List records from an untyped collection
         * @param {RecordsApiListCollectionRecordsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCollectionRecords(requestParameters: RecordsApiListCollectionRecordsRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericRecordPage> {
            return localVarFp.listCollectionRecords(requestParameters.gameId, requestParameters.collectionId, requestParameters.pageSize, requestParameters.cursor, requestParameters.fields, requestParameters.sort, requestParameters.language, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecordsApi - interface
 */
export interface RecordsApiInterface {
    /**
     * 
     * @summary Get an untyped collection record
     * @param {RecordsApiGetCollectionRecordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCollectionRecord(requestParameters: RecordsApiGetCollectionRecordRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericRecordResponse>;

    /**
     * Advanced escape hatch for collections that do not yet have a typed Darkclaw resource. Prefer a typed endpoint when one exists. 
     * @summary List records from an untyped collection
     * @param {RecordsApiListCollectionRecordsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCollectionRecords(requestParameters: RecordsApiListCollectionRecordsRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenericRecordPage>;

}

/**
 * Request parameters for getCollectionRecord operation in RecordsApi.
 */
export interface RecordsApiGetCollectionRecordRequest {
    /**
     * Stable Darkclaw game identifier.
     */
    readonly gameId: GetCollectionRecordGameIdEnum

    readonly collectionId: string

    readonly recordId: string

    /**
     * Comma-separated response fields to include.
     */
    readonly fields?: string

    /**
     * Preferred language for localized values.
     */
    readonly language?: GetCollectionRecordLanguageEnum
}

/**
 * Request parameters for listCollectionRecords operation in RecordsApi.
 */
export interface RecordsApiListCollectionRecordsRequest {
    /**
     * Stable Darkclaw game identifier.
     */
    readonly gameId: ListCollectionRecordsGameIdEnum

    readonly collectionId: string

    /**
     * Maximum records returned in this page.
     */
    readonly pageSize?: number

    /**
     * Opaque cursor returned by the previous page.
     */
    readonly cursor?: string

    /**
     * Comma-separated response fields to include.
     */
    readonly fields?: string

    /**
     * Comma-separated fields, prefixed with &#x60;-&#x60; for descending order.
     */
    readonly sort?: string

    /**
     * Preferred language for localized values.
     */
    readonly language?: ListCollectionRecordsLanguageEnum
}

/**
 * RecordsApi - object-oriented interface
 */
export class RecordsApi extends BaseAPI implements RecordsApiInterface {
    /**
     * 
     * @summary Get an untyped collection record
     * @param {RecordsApiGetCollectionRecordRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCollectionRecord(requestParameters: RecordsApiGetCollectionRecordRequest, options?: RawAxiosRequestConfig) {
        return RecordsApiFp(this.configuration).getCollectionRecord(requestParameters.gameId, requestParameters.collectionId, requestParameters.recordId, requestParameters.fields, requestParameters.language, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Advanced escape hatch for collections that do not yet have a typed Darkclaw resource. Prefer a typed endpoint when one exists. 
     * @summary List records from an untyped collection
     * @param {RecordsApiListCollectionRecordsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listCollectionRecords(requestParameters: RecordsApiListCollectionRecordsRequest, options?: RawAxiosRequestConfig) {
        return RecordsApiFp(this.configuration).listCollectionRecords(requestParameters.gameId, requestParameters.collectionId, requestParameters.pageSize, requestParameters.cursor, requestParameters.fields, requestParameters.sort, requestParameters.language, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetCollectionRecordGameIdEnum = {
    Eq: 'eq',
    Eq2: 'eq2',
    Mtg: 'mtg',
    Dcu: 'dcu',
    Ps: 'ps',
    Ps2: 'ps2',
    Ps2ps4us: 'ps2ps4us',
    Ps2ps4eu: 'ps2ps4eu',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type GetCollectionRecordGameIdEnum = typeof GetCollectionRecordGameIdEnum[keyof typeof GetCollectionRecordGameIdEnum];
export const GetCollectionRecordLanguageEnum = {
    En: 'en',
    De: 'de',
    Es: 'es',
    Fr: 'fr',
    It: 'it',
    Ja: 'ja',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type GetCollectionRecordLanguageEnum = typeof GetCollectionRecordLanguageEnum[keyof typeof GetCollectionRecordLanguageEnum];
export const ListCollectionRecordsGameIdEnum = {
    Eq: 'eq',
    Eq2: 'eq2',
    Mtg: 'mtg',
    Dcu: 'dcu',
    Ps: 'ps',
    Ps2: 'ps2',
    Ps2ps4us: 'ps2ps4us',
    Ps2ps4eu: 'ps2ps4eu',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type ListCollectionRecordsGameIdEnum = typeof ListCollectionRecordsGameIdEnum[keyof typeof ListCollectionRecordsGameIdEnum];
export const ListCollectionRecordsLanguageEnum = {
    En: 'en',
    De: 'de',
    Es: 'es',
    Fr: 'fr',
    It: 'it',
    Ja: 'ja',
    UnknownDefaultOpenApi: '11184809',
} as const;
export type ListCollectionRecordsLanguageEnum = typeof ListCollectionRecordsLanguageEnum[keyof typeof ListCollectionRecordsLanguageEnum];


