# coding: utf-8

"""
    Darkclaw API

    A modern, stable interface to game data sourced from Darkpaw Games Census. Darkclaw normalizes upstream paths, parameters, payloads, pagination, and errors so consumers never need to depend on Census-specific conventions.  Darkclaw is unofficial and is not affiliated with or endorsed by Darkpaw Games. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from darkclaw_census_api_client.models.character_page import CharacterPage

class TestCharacterPage(unittest.TestCase):
    """CharacterPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CharacterPage:
        """Test CharacterPage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CharacterPage`
        """
        model = CharacterPage()
        if include_optional:
            return CharacterPage(
                data = [
                    darkclaw_census_api_client.models.character.Character(
                        id = '4', 
                        name = darkclaw_census_api_client.models.character_name.CharacterName(
                            first = '', 
                            last = '', ), 
                        display_name = '', 
                        profile = darkclaw_census_api_client.models.character_profile.CharacterProfile(
                            class_id = 56, 
                            class_name = '', 
                            race_id = 56, 
                            race_name = '', 
                            level = 1, 
                            gender = '', 
                            deity = '', 
                            alignment = 56, ), 
                        location = darkclaw_census_api_client.models.character_location.CharacterLocation(
                            server_id = 56, 
                            server_name = '', 
                            zone_name = '', 
                            coordinates = '', ), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                page = darkclaw_census_api_client.models.page_metadata.PageMetadata(
                    page_size = 1, 
                    returned = 0, 
                    next_cursor = '', )
            )
        else:
            return CharacterPage(
                data = [
                    darkclaw_census_api_client.models.character.Character(
                        id = '4', 
                        name = darkclaw_census_api_client.models.character_name.CharacterName(
                            first = '', 
                            last = '', ), 
                        display_name = '', 
                        profile = darkclaw_census_api_client.models.character_profile.CharacterProfile(
                            class_id = 56, 
                            class_name = '', 
                            race_id = 56, 
                            race_name = '', 
                            level = 1, 
                            gender = '', 
                            deity = '', 
                            alignment = 56, ), 
                        location = darkclaw_census_api_client.models.character_location.CharacterLocation(
                            server_id = 56, 
                            server_name = '', 
                            zone_name = '', 
                            coordinates = '', ), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                page = darkclaw_census_api_client.models.page_metadata.PageMetadata(
                    page_size = 1, 
                    returned = 0, 
                    next_cursor = '', ),
        )
        """

    def testCharacterPage(self):
        """Test CharacterPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
