# coding: utf-8

"""
    Darkclaw API

    A modern, stable interface to game data sourced from Darkpaw Games Census. Darkclaw normalizes upstream paths, parameters, payloads, pagination, and errors so consumers never need to depend on Census-specific conventions.  Darkclaw is unofficial and is not affiliated with or endorsed by Darkpaw Games. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from darkclaw_census_api_client.models.collection_list_response import CollectionListResponse

class TestCollectionListResponse(unittest.TestCase):
    """CollectionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionListResponse:
        """Test CollectionListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionListResponse`
        """
        model = CollectionListResponse()
        if include_optional:
            return CollectionListResponse(
                data = [
                    darkclaw_census_api_client.models.collection.Collection(
                        id = '', 
                        record_count = 0, 
                        hidden = True, 
                        indexes = [
                            [
                                ''
                                ]
                            ], 
                        resolvers = [
                            ''
                            ], )
                    ]
            )
        else:
            return CollectionListResponse(
                data = [
                    darkclaw_census_api_client.models.collection.Collection(
                        id = '', 
                        record_count = 0, 
                        hidden = True, 
                        indexes = [
                            [
                                ''
                                ]
                            ], 
                        resolvers = [
                            ''
                            ], )
                    ],
        )
        """

    def testCollectionListResponse(self):
        """Test CollectionListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
