# coding: utf-8

"""
    Darkclaw API

    A modern, stable interface to game data sourced from Darkpaw Games Census. Darkclaw normalizes upstream paths, parameters, payloads, pagination, and errors so consumers never need to depend on Census-specific conventions.  Darkclaw is unofficial and is not affiliated with or endorsed by Darkpaw Games. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from darkclaw_census_api_client.models.character_profile import CharacterProfile

class TestCharacterProfile(unittest.TestCase):
    """CharacterProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CharacterProfile:
        """Test CharacterProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CharacterProfile`
        """
        model = CharacterProfile()
        if include_optional:
            return CharacterProfile(
                class_id = 56,
                class_name = '',
                race_id = 56,
                race_name = '',
                level = 1,
                gender = '',
                deity = '',
                alignment = 56
            )
        else:
            return CharacterProfile(
        )
        """

    def testCharacterProfile(self):
        """Test CharacterProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
