# coding: utf-8

"""
    Darkclaw API

    A modern, stable interface to game data sourced from Darkpaw Games Census. Darkclaw normalizes upstream paths, parameters, payloads, pagination, and errors so consumers never need to depend on Census-specific conventions.  Darkclaw is unofficial and is not affiliated with or endorsed by Darkpaw Games. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from darkclaw_census_api_client.api.ever_quest_ii_characters_api import EverQuestIICharactersApi


class TestEverQuestIICharactersApi(unittest.TestCase):
    """EverQuestIICharactersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EverQuestIICharactersApi()

    def tearDown(self) -> None:
        pass

    def test_get_character(self) -> None:
        """Test case for get_character

        Get an EverQuest II character
        """
        pass

    def test_list_characters(self) -> None:
        """Test case for list_characters

        Search EverQuest II characters
        """
        pass


if __name__ == '__main__':
    unittest.main()
