# coding: utf-8

"""
    Darkclaw API

    A modern, stable interface to game data sourced from Darkpaw Games Census. Darkclaw normalizes upstream paths, parameters, payloads, pagination, and errors so consumers never need to depend on Census-specific conventions.  Darkclaw is unofficial and is not affiliated with or endorsed by Darkpaw Games. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from darkclaw_census_api_client.api.records_api import RecordsApi


class TestRecordsApi(unittest.TestCase):
    """RecordsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecordsApi()

    def tearDown(self) -> None:
        pass

    def test_get_collection_record(self) -> None:
        """Test case for get_collection_record

        Get an untyped collection record
        """
        pass

    def test_list_collection_records(self) -> None:
        """Test case for list_collection_records

        List records from an untyped collection
        """
        pass


if __name__ == '__main__':
    unittest.main()
